### ISSUE TITLE
Результаты верификации

### ISSUE THREAD

**Issue by vmironovich** [mbuzdalov/latex-styles#13]
- Магистерская диссертация, а не "пояснительная записка магистерской диссертации"
- Стандартное направление подготовки (специальность): 01.04.02 Прикладная математика и информатика
- Стандартная направленность (профиль): Технологии проектирования и разработки программного обеспечения 
- На обратной стороне титульного листа "Направленность (профиль), специализация" выделить жирным
- Срок сдачи студентом работы - любой не выходной день мая\июня до защиты (01.06.2016 звучит видимо адекватно)
- Дата выдачи задания 01.09.2014 (магистры, это понедельник), такая же дата в "принял к исполнению"
- В аннотации если какая-то нумерованная часть разбивается и переноситься на следующую страницу, хотелось бы переносить целиком (возможно можно просто перенести с 8. Краткая характеристика, и будет норм)
- Вдогонку в задании "студенту" требует склонения фамилии, сделать "Студент"?

**Comment by mbuzdalov** [comment]
"Стандартная направленность (профиль): Технологии проектирования и разработки программного обеспечения" - это для магистров. Для бакалавров - "Математические модели и алгоритмы разработки программного обеспечения".
