### ISSUE TITLE
Неправильный титульный лист

### ISSUE THREAD

**Issue by sslavian812** [mbuzdalov/latex-styles#26]
Титульный лист не такой. Возможно аннотация и задание тоже неправильные 

http://kgeorgiy.info/ctd/index.html

**Comment by mbuzdalov** [comment]
Вот какого это пишется только сейчас, когда уже защиты, а не в тот же день, когда это стало известно?!

**Comment by sslavian812** [comment]
@mbuzdalov 
Я узнал вчера вечером, когда пришел сдавать подшитый диплом.

**Comment by loskutov** [comment]
На случай, если кому-то окажется полезно: [подкостыленный шаблон](https://hastebin.com/igiyivanaq.tex), более или менее реализующий требуемый вид титульного листа и задания-аннотации для бакалавров.

**Comment by Oktai15** [comment]
Титульный лист все еще не соответствует ГОСТу?

**Comment by Oktai15** [comment]
С этого года вроде как отсутствуют кафедры в ИТМО, а значит шаблон значительно поменяется :(

**Comment by mbuzdalov** [comment]
В ближайшее время буду все это глобально чинить. Вероятно, мне все-таки показали правильные шаблоны на этот год.

**Comment by pva701** [comment]
![image](https://user-images.githubusercontent.com/7355273/56392676-b6711400-623a-11e9-8a46-dea190e566ec.png)
