### ISSUE TITLE
Переименовать Министерство образования и науки

### ISSUE THREAD

**Issue by jrogov** [mbuzdalov/latex-styles#30]
Министерство образования было разделено на Министерство просвещения и Министерство науки и высшего образования. (пруф: https://tass.ru/politika/5203399)

Уже требуют изменять в официальных документах на предстоящую защиту.

Таким образом, нужно переименовать
- Министерство образования и науки Российской Федерации
на
- Министерство науки и высшего образования Российской Федерации

**Comment by mbuzdalov** [comment]
Уже исправлено ощутимое время назад. Вы проверяли свежую версию?

**Comment by jrogov** [comment]
Прошу прощения, вы правы.
Форкнул некоторое время назад, забыл про это и не обновил.
