### ISSUE TITLE
Некорректные шаблоны для второстепенных документов

### ISSUE THREAD

**Issue by DrDet** [mbuzdalov/latex-styles#34]
В начале учебного года произошли какие-то изменения в юридическом аспекте университета ИТМО. Например, поменялось его название.
В связи с этим шаблоны для таких документов как specification, annotation и т.д. генерируются некорректно. В связи с приближающейся защитой/предзащитой хотелось бы, чтобы они были актуализированы.

**Comment by mbuzdalov** [comment]
Кажется, пофикшено в последнем пуше, который сливал изменения @GoPavel и мои аналогичные изменения.
