### ISSUE TITLE
Долгая компиляция на современных дистрибутивах (TeX Live 2022, MiKTeX 22.10)

### ISSUE THREAD

**Issue by geranazavr555** [mbuzdalov/latex-styles#39]
При использовании шаблона в overleaf и TeX Live 2022 компиляция прерывается по лимиту времени. Если сменить версию на TeX Live 2021, проблема исчезает.

Аналогичная проблема при компиляции на MiKTeX 22.10 -- компиляция длится около получаса, после чего xelatex падает (! TeX capacity exceeded, sorry)

**Comment by mbuzdalov** [comment]
На примерах это тоже проявляется, или только на каких-то конкретных документах?

**Comment by geranazavr555** [comment]
Прямо на bachelor-thesis.tex из этого репозитория. Выяснил, что проблема в \maketitle{Бакалавр}. Если его закомментировать и, чтобы компилировалось, в itmo-student-thesis.cls добавить \newcommand{\TheOnlyTruePageStyle}{fancy} в конце, проблема исчезает.

**Comment by mbuzdalov** [comment]
Я нашел одну штуку, которая, возможно, это вызывает. Посмотрите свежую версию, пожалуйста.

**Comment by geranazavr555** [comment]
Проблема решена, протестировано на TeX Live 2022 и MiKTeX 22.10. Спасибо!
